fix typo in msearch guide (index -> indices)
It causes "TypeError: client.index.refresh is not a function" when trying to run the sample codes in msearch.md.

Signed-off-by: Wei Sun <wei.sun10@microfocus.com>