Update search.md
Getting an error when omitting the body parameter. 

   ConfigurationError: Missing required parameter: body

      114 |         })
      115 |
    > 116 |         await ds.client.index({ index: "movies", refresh: true })
          |                         ^
      117 |       })
      118 |       afterAll(async () => {
      119 |         await ds.client.indices.delete({ index: "movies" })

      at Client.indexApi [as index] (node_modules/@opensearch-project/opensearch/api/api/index.js:103:17)
      at Object.index (classes/tests/app_datasource_opensearch.e2e.test.js:116:25)

Signed-off-by: romaincomeau <92224046+romaincomeau@users.noreply.github.com>